modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="supersells"
version="1.0"
displayName="Super Sells"
description='''
Addon for Applied Energistics 2
'''

[[dependencies.supersells]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.supersells]]
    modId="appliedenergistics2"
    mandatory=true
    versionRange="[8.4.7,)"
    ordering="AFTER"
    side="BOTH"